### ISSUE TITLE
大佬，想问下浏览器标签前面的ICON是怎么换的

### ISSUE THREAD

**Issue by erdaxia** [BigCoke233/matcha#1]
纯小白，之前用的主题在设置里会有替换ICON的栏目，但是您这个我找了下没有找到想问下怎么替换啊T T

**Comment by BigCoke233** [comment]
我本来是打算弄一个这样的设置的，你没提醒我还差点忘了，晚点就安排上。目前，你可以在网站根目录，放一个名为 favicon.png 的图片来替换浏览器显示的图标。
