### ISSUE TITLE
搜索的bug

### ISSUE THREAD

**Issue by r0mancey** [BigCoke233/matcha#10]
关于搜索目前有几个问题想要反馈
1. 右上角的搜索按钮：它的功能是未实装吗，它没有可供点击的按钮，而使用回车键也无法执行搜索
![image](https://user-images.githubusercontent.com/102581259/192671802-330c8259-4ac8-4300-81b6-4e6ac62f4dd1.png)
2. 归档页面的搜索框：这里能否也加上使用回车执行搜索的功能，一开始琢磨了好久才意识到是点击按钮搜索
![image](https://user-images.githubusercontent.com/102581259/192673067-d3969c0e-7f4f-4a9a-8ab2-ebe9c9aa7758.png)
3. 您的博客：目前您的博客在归档页面进行过搜索后将不再使用https，页面部分图标加载不了，而且页面pjax也失效了
![image](https://user-images.githubusercontent.com/102581259/192674706-fcb40c14-2429-4d29-9c30-9530c81f0936.png)

**Comment by 9bingyin** [comment]
右上角搜索正常是这样的，可能是作者插件没设置好（？）
![image](https://user-images.githubusercontent.com/37502927/192709791-3aee6c12-c696-4130-8536-75c21e7be2e7.png)

**Comment by BigCoke233** [comment]
第一个是插件的原因，我这边改了下设置就行了；另外两项已经修复，感谢反馈
