### ISSUE TITLE
主题搜索插件及CDN问题

### ISSUE THREAD

**Issue by moxv** [BigCoke233/matcha#12]
主题搜索插件加载导致文章发表错误，主题CDN打开与否加载缓慢，一直转圈

**Comment by moxv** [comment]
![image](https://user-images.githubusercontent.com/37197578/197915507-cbbb452f-c445-4f10-b6c3-ddee96f611ae.png)

**Comment by moxv** [comment]
主题一定有问题，我服务器上重新安装，还是不停加载，要不就是主题CDN引用问题

**Comment by BigCoke233** [comment]
请给出有问题的链接，并提供你的运行环境，你这样根本没法诊断问题

**Comment by moxv** [comment]
我没有用cdn，用的腾讯轻量云，默认配置，1.2版typecho，主题版本最新版1.0.2

**Comment by moxv** [comment]
https://seersu.top

**Comment by BigCoke233** [comment]
很明显你引入了多个 jQuery，导致了 pjax 等多个功能失效，所以才会一直处于加载状态，请在 ExSearch 插件设置里关闭 jQuery 引入。

另外，这个问题的解决方案在 [FAQ](https://github.com/BigCoke233/matcha/blob/main/doc.md) 的第六条里有提到。

**Comment by moxv** [comment]
> 很明显你引入了多个 jQuery，导致了 pjax 等多个功能失效，所以才会一直处于加载状态，请在 ExSearch 插件设置里关闭 jQuery 引入。
> 
> 另外，这个问题的解决方案在 [FAQ](https://github.com/BigCoke233/matcha/blob/main/doc.md) 的第六条里有提到。

抱歉，博主，我是新手，很多问题也不知道怎么组织语言形容，确实鲁莽了，谅解，最后再问下，贵站使用的字体及实现方法。您的主题很不错，很喜欢，谢谢贡献处这么好的主题，再接再厉！

**Comment by BigCoke233** [comment]
我使用的字体都写在主题里了。要问实现方法的话，用的是 [Google Fonts](https://fonts.google.com)，然后引入对应的 css 文件。

**Comment by moxv** [comment]
谢谢博主

**Comment by moxv** [comment]
谢谢博主
