### ISSUE TITLE
评论必须填写邮箱，与设置不同。

### ISSUE THREAD

**Issue by mai1202** [BigCoke233/matcha#15]
这个主题好像未遵循设置的「必须填写邮箱」选项，评论必须填写邮箱，希望修复一下这个bug。

**Comment by mai1202** [comment]
还有退出登录时会报错ERR_TOO_MANY_REDIRECTS，提示「该网页无法正常运作，网站将您重定向的次数过多。」

**Comment by KurococLiu** [comment]
> 还有退出登录时会报错ERR_TOO_MANY_REDIRECTS，提示“该网页无法正常运行，网站将您重定向的次数过多。”

建议检查一下CDN或者宝塔设置

**Comment by mai1202** [comment]
> > 还有退出登录时会报错ERR_TOO_MANY_REDIRECTS，提示“该网页无法正常运行，网站将您重定向的次数过多。”
> 
> 建议检查一下CDN或者宝塔设置

我直接在管理页面登出就没问题，Cloudflare 加密模式用的也是「完全（严格）」
