### ISSUE TITLE
文章无法生成目录

### ISSUE THREAD

**Issue by youyou-sudo** [BigCoke233/matcha#18]
我搬运了一篇较长的文章：[提问的智慧](https://www.jerryyang.link/index.php/archives/5)
我确认文章没有任何一级标题
![image](https://user-images.githubusercontent.com/60727068/222438264-a1150afa-c372-4834-975d-1ce14a269601.png)
并确认我设置开启目录 
![image](https://user-images.githubusercontent.com/60727068/222438346-85920115-c376-4bc5-8a10-8ab9321da21f.png)
但无法展示生成目录
![image](https://user-images.githubusercontent.com/60727068/222438992-c53832f8-7a13-47c5-8fee-1018e4394a38.png)
不过其他短一点的文章目录可以正常显示，如：[一加手机刷入类原生](https://www.jerryyang.link/index.php/archives/6/)
![image](https://user-images.githubusercontent.com/60727068/222439249-49865a08-82cf-431b-bc44-9429205fa96f.png)

**Comment by cyolc932** [comment]
@BigCoke233 老哥
有位网友在站点内的`home`子文件夹内使用了您的主题 
但子文件夹内的搜索功能无法使用
这是它的站点搜索页 https://域名/`home`/index.php/archive
跳转后变成https://域名/index.php/search/搜索关键词/ 显示404
链接缺少`home`，请问这个可以修改哪个文件修复

**Comment by BigCoke233** [comment]
> @BigCoke233 老哥 有位网友在站点内的`home`子文件夹内使用了您的主题 站点首页链接是[https://域名/home](https://%E5%9F%9F%E5%90%8D/home) ![图片](https://private-user-images.githubusercontent.com/46415893/258560842-6e7f345b-331d-474f-adec-37deecf40c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjUzNDIsIm5iZiI6MTcwMjg2NTA0MiwicGF0aCI6Ii80NjQxNTg5My8yNTg1NjA4NDItNmU3ZjM0NWItMzMxZC00NzRmLWFkZWMtMzdkZWVjZjQwYzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAyMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTgwZGZkZjliZjdmNzhmNTQ2N2NmMmRlZjNkMTliNmU2MmIzZTk2ZGFmODdmZTU2NGRlZjQ5MGM5OGFiZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q2VmQTYtnFRSREnFkLWiRzuPxDdYR5C1tZnJ-b2ThrY)
> 
> 但子文件夹内的搜索功能无法使用 这是它的站点搜索页 [https://域名/home/index.php/archive](https://%E5%9F%9F%E5%90%8D/home/index.php/archive) 链接含有`home` 跳转后变成[https://域名/index.php/search/搜索关键词/](https://%E5%9F%9F%E5%90%8D/index.php/search/%E6%90%9C%E7%B4%A2%E5%85%B3%E9%94%AE%E8%AF%8D/) 显示404 链接缺少`home`，请问这个可以修改哪个文件来修复此问题 ![图片](https://private-user-images.githubusercontent.com/46415893/258560833-52375687-593c-4798-94da-a4c8d660d5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjUzNDIsIm5iZiI6MTcwMjg2NTA0MiwicGF0aCI6Ii80NjQxNTg5My8yNTg1NjA4MzMtNTIzNzU2ODctNTkzYy00Nzk4LTk0ZGEtYTRjOGQ2NjBkNWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAyMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMjE3Yzg4MTc4NjYyMmNmODQ0M2ZjN2ZiZjRhZGNlZWQ4Y2I4NWFjNGI5NTY4MDU5NmYyY2UyMGY1YTdmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AREm6-wT0_tgOecUVIJ831-3_B-wh7bRpdVzLBu2B8M)

一般不建议把博客放在子目录，我在设计的时候没有考虑到这个问题。

另外下次提问题请新建一个 Issue，不要在别人的楼下直接回复
