### ISSUE TITLE
大佬求救，独立页面在手机端不能正常显示

### ISSUE THREAD

**Issue by erdaxia** [BigCoke233/matcha#2]
新增的独立页面在手机端IPHONE和小米VIA都不能正常显示，点击以后会刷新页面到主页，网站下的计数会加一。

但是我用手机看你的网页又是正常能进入的。。。完全不知道哪里搞错了。。。

**Comment by BigCoke233** [comment]
这个问题确实存在 等我排查一下

**Comment by BigCoke233** [comment]
破案了，是 Ringo 主题遗留的问题，你替换一下 includes/header.php 就行了

**Comment by erdaxia** [comment]
> 

谢谢大佬~

**Comment by erdaxia** [comment]
完美解决~大佬666~
