### ISSUE TITLE
【求助】左侧导航栏可以加分类页面吗

### ISSUE THREAD

**Issue by StrawHat179** [BigCoke233/matcha#33]
博主，我想问一下，这个博客主题侧边栏可以加分类页面吗?就是导航栏上显示某个分类目录（或者二级标签这种），看了你的源码，不懂php🤣，如果方便的话告知一下，不甚感激
![image](https://github.com/BigCoke233/matcha/assets/104472839/fa745664-2183-41d3-977b-4d39d8fa866b)

**Comment by LiCaoZ** [comment]
你或许希望的是 #24 中已实现的功能🤔
