### ISSUE TITLE
添加对于 CaptchaPlus 插件的支持

### ISSUE THREAD

**Issue by 9bingyin** [BigCoke233/matcha#34]
希望可以添加一下
https://github.com/scenery/typecho-plugins#captchaplus

**Comment by BigCoke233** [comment]
目前 Matcha 主题已经停止更新，所有包括适配插件等在内的新功能都不会被添加，因为个人精力问题不能维护这个项目，还请谅解。另外，这个代码的适配并不困难，按照你所提供的链接中的描述修改应该就能实现。
