### ISSUE TITLE
如何设置首页导航

### ISSUE THREAD

**Issue by souduck** [BigCoke233/matcha#44]
<img width="414" alt="image" src="https://github.com/BigCoke233/matcha/assets/107752244/2c4a89cb-dcac-4c83-9ace-19aa1ced2940">
 请问如何设置首页导航呢

**Comment by BigCoke233** [comment]
这个在主题的[使用文档](https://matcha.guhub.cn/config#%E9%A6%96%E9%A1%B5%E7%9B%B8%E5%85%B3%E9%93%BE%E6%8E%A5)里有些，下次遇到问题请先查看文档
