### ISSUE TITLE
無法訪問文檔了

### ISSUE THREAD

**Issue by Zibuger** [BigCoke233/matcha#46]
您好，請問如何訪問這個主題的建設文檔呢

**Comment by KuanRe** [comment]
域名更换了， https://matcha.corpusi.com/

**Comment by BigCoke233** [comment]
文档无法访问的问题已经修复，现在应该可以通过 https://matcha.corpusi.com 正常访问

如果再次出现这种问题，访问 https://bigcoke233.github.io/matcha-wiki
