### ISSUE TITLE
Ver.1.1.0-beta.2 先行版，出现报错。

### ISSUE THREAD

**Issue by MurphyZX** [BigCoke233/matcha#5]
页面最上方提示报错，信息如下：
Warning: Undefined array key "matchaDark" in /www/wwwroot/blog.liamm.cn/usr/themes/matcha/libs/Matcha.php on line 400
控制台报错信息：
![image](https://user-images.githubusercontent.com/61101985/187614618-66fbc985-d27d-4c09-a0a8-6ef572ae1471.png)
![image](https://user-images.githubusercontent.com/61101985/187614764-2d273edf-50f7-4a17-acd8-2328b0c133c1.png)
博客地址：
https://blog.liamm.cn/

**Comment by MurphyZX** [comment]
> 页面最上方提示报错，信息如下： Warning: Undefined array key "matchaDark" in /www/wwwroot/blog.liamm.cn/usr/themes/matcha/libs/Matcha.php on line 400 控制台报错信息： ![image](https://user-images.githubusercontent.com/61101985/187614618-66fbc985-d27d-4c09-a0a8-6ef572ae1471.png) ![image](https://user-images.githubusercontent.com/61101985/187614764-2d273edf-50f7-4a17-acd8-2328b0c133c1.png) 博客地址： https://blog.liamm.cn/

php切换到7.4可以了，之前是8.0

**Comment by MurphyZX** [comment]
> 页面最上方提示报错，信息如下： Warning: Undefined array key "matchaDark" in /www/wwwroot/blog.liamm.cn/usr/themes/matcha/libs/Matcha.php on line 400 控制台报错信息： ![image](https://user-images.githubusercontent.com/61101985/187614618-66fbc985-d27d-4c09-a0a8-6ef572ae1471.png) ![image](https://user-images.githubusercontent.com/61101985/187614764-2d273edf-50f7-4a17-acd8-2328b0c133c1.png) 
博客地址： https://blog.liamm.cn/

php切换到7.4可以了，之前是8.0

**Comment by BigCoke233** [comment]
这个不是 php 版本的问题，确实是 bug，但是在开发板修复了
